### ISSUE TITLE
Wrong Docker name

### ISSUE THREAD

**Issue by contradictioned** [coin-or-tools/optimization-suite-docker#1]
This is the output of the README's suggestion:

`$ docker pull tkralphs/optimization-suite-docker`

> Using default tag: latest
> Error response from daemon: pull access denied for tkralphs/optimization-suite-docker, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

I guess, the correct image is this https://hub.docker.com/r/tkralphs/coinor-optimization-suite ?

**Comment by tkralphs** [comment]
Yes, you are right. I accidentally had two identical images with different names and deleted the duplicate. I will update the documentation now.
