### ISSUE TITLE
Wrong Docker name

### ISSUE THREAD

**Issue by BeiYinZhiNian** [coin-or-tools/optimization-suite-docker#2]
README.md 

docker pull coinor/coinor-optimization-suite

Error response from daemon: pull access denied for coinor/coinor-optimization-suite, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

It doesn't exist，The correct answer should be

docker pull coinor/coin-or-optimization-suite

**Comment by tkralphs** [comment]
Fixed in f4cd2ce0aedb63ac0e4129e60e1c56714209ec84. Thanks!
